#!/bin/bash

echo "========================================="
echo "   MONSTA Platform - Render Deployment"
echo "========================================="
echo ""

# Render.com 자동 배포 설정
echo "Render.com 배포 단계:"
echo ""
echo "1. Render.com 계정 생성 (무료):"
echo "   https://render.com"
echo ""
echo "2. GitHub 저장소 연결:"
echo "   - New > Web Service 클릭"
echo "   - GitHub 저장소 'monstas7' 선택"
echo ""
echo "3. 서비스 설정:"
echo "   - Name: monsta-platform"
echo "   - Runtime: Docker"
echo "   - Plan: Free"
echo ""
echo "4. 환경 변수 추가:"
echo "   - BINANCE_API_KEY"
echo "   - BINANCE_API_SECRET"
echo "   - DATABASE_URL (자동 생성)"
echo ""
echo "5. 데이터베이스 생성:"
echo "   - New > PostgreSQL 클릭"
echo "   - Name: monsta-db"
echo "   - Plan: Free"
echo ""
echo "배포가 자동으로 시작됩니다!"
echo ""
echo "대안: Heroku 배포"
echo "==================="
echo "heroku create monstas7"
echo "heroku addons:create heroku-postgresql:mini"
echo "heroku addons:create heroku-redis:mini"
echo "git push heroku master"
echo ""