name: Check Server Status

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Server Status
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 13.209.84.93
          username: ubuntu
          key: ${{ secrets.AWS_SERVER_KEY }}
          script: |
            echo "=== 서버 상태 확인 ==="
            echo "현재 시간: $(date)"
            echo ""
            
            echo "1. PM2 프로세스 상태:"
            pm2 status || echo "PM2가 실행중이지 않습니다"
            echo ""
            
            echo "2. Node 프로세스:"
            ps aux | grep node | grep -v grep || echo "Node 프로세스 없음"
            echo ""
            
            echo "3. 포트 사용 현황:"
            sudo netstat -tlnp | grep -E "3000|8000" || echo "포트 3000, 8000 사용중이지 않음"
            echo ""
            
            echo "4. 최근 PM2 로그 (에러):"
            pm2 logs --lines 30 --err --nostream || echo "PM2 로그 없음"
            echo ""
            
            echo "5. 프로젝트 디렉토리 확인:"
            ls -la ~/monstas7/frontend/ | head -10
            echo ""
            
            echo "6. .env.local 파일 존재 여부:"
            if [ -f ~/monstas7/frontend/.env.local ]; then
              echo ".env.local 파일이 존재합니다"
              echo "파일 크기: $(ls -la ~/monstas7/frontend/.env.local | awk '{print $5}') bytes"
            else
              echo ".env.local 파일이 없습니다!"
            fi
            echo ""
            
            echo "7. node_modules 존재 여부:"
            if [ -d ~/monstas7/frontend/node_modules ]; then
              echo "node_modules 디렉토리가 존재합니다"
            else
              echo "node_modules 디렉토리가 없습니다!"
            fi
            echo ""
            
            echo "8. .next 빌드 디렉토리 존재 여부:"
            if [ -d ~/monstas7/frontend/.next ]; then
              echo ".next 빌드 디렉토리가 존재합니다"
            else
              echo ".next 빌드 디렉토리가 없습니다!"
            fi
            echo ""
            
            echo "9. 로컬 테스트:"
            curl -I http://localhost:3000 2>/dev/null | head -5 || echo "로컬 연결 실패"
            echo ""
            
            echo "10. 메모리 사용량:"
            free -m
            echo ""
            
            echo "11. 디스크 사용량:"
            df -h | grep -E "/$|/dev/"