name: Simple Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 13.209.84.93
          username: ubuntu
          key: ${{ secrets.AWS_SERVER_KEY }}
          timeout: 30m
          command_timeout: 30m
          script: |
            # 로그 시작
            echo "=== 배포 시작: $(date) ==="
            
            # 1. 모든 프로세스 정리
            echo "1. 프로세스 정리..."
            pm2 stop all || true
            pm2 delete all || true
            pkill -f node || true
            pkill -f npm || true
            
            # 2. 프로젝트 업데이트
            echo "2. 코드 업데이트..."
            cd ~/monstas7
            git pull origin master
            
            # 실행 권한 부여
            chmod +x scripts/server-restart.sh
            
            # 3. 스크립트 실행
            echo "3. 서버 재시작 스크립트 실행..."
            bash scripts/server-restart.sh
            
            echo "=== 배포 완료: $(date) ==="