name: Force Restart

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  force:
    runs-on: ubuntu-latest
    
    steps:
      - name: Force Server Start
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 13.209.84.93
          username: ubuntu
          key: ${{ secrets.AWS_SERVER_KEY }}
          timeout: 10m
          script: |
            # 강제 시작
            cd ~/monstas7/frontend 2>/dev/null || cd ~/monsta-v7/monstas7/frontend 2>/dev/null || {
              cd ~
              rm -rf monstas7
              git clone https://github.com/loadstar0723/monstas7.git
              cd monstas7/frontend
            }
            
            # 모든 것 종료
            killall -9 node npm 2>/dev/null || true
            pm2 kill 2>/dev/null || true
            
            # 최신 코드
            git pull
            
            # .next 삭제
            rm -rf .next
            
            # 패키지 설치
            [ ! -d node_modules ] && npm install
            
            # 바로 실행
            PORT=3000 npm run dev > /dev/null 2>&1 &
            
            echo "PID: $!"
            sleep 10
            
            # 확인
            curl -I localhost:3000 || {
              PORT=3000 nohup npm run dev > ~/app.log 2>&1 &
              echo "Retry PID: $!"
            }
            
            echo "✅ Started: http://13.209.84.93:3000"